name: Build Geyser
on:
  push:
    branches:
    - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.pagesdeployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - uses: actions/setup-node@v3.5.0
        name: Setup Node.js
        with:
          node-version: 18.x

      - name: Build with Gradle
        run: ./gradlew build

      - name: Move files and index
        run: |
          mkdir tmpPages/
          mv -fv bootstrap/*/build/libs/*.jar tmpPages/
          cd tmpPages/
          sudo npm i -g index-pages
          apindex .

      - uses: actions/upload-pages-artifact@v1
        name: Upload artifact
        with:
          path: "tmpPages"

      - uses: actions/deploy-pages@v1
        id: pagesdeployment
        name: Deploy to GitHub Pages